name: E2E UI tests
on:
  workflow_dispatch:
    browser:
      type: choice
      description: browser
      default: any
      options:
        - 'any'
        - 'chromium'
        - 'firefox'
        - 'webkit'
        - 'Mobile Chrome'
        - 'Mobile Safari'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests for a specific project
        if: ${{ github.event.inputs.browser }} != 'any'
        run: npx playwright test --project=${{ github.event.inputs.browser }}
      - name: Run tests for all ui projects
        if: ${{ github.event.inputs.browser }} == 'any'
        run: npm run test:e2e:ui
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
